version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aim
    ports:
      - "5432:5432"
  
  # Spring Boot 
  app:
    image: weaponvault-app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aim
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8081:8081" 
