spring.application.name=WeaponVault
server.port=8081

# Database connection settings (Uses environment variables, with local defaults)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aim}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger



#spring.web.cors.allowed-origins=*
#spring.web.cors.allowed-methods=*
#spring.web.cors.allowed-headers=*
#Logging
#logging.file.name=${LOGGING_FILE_NAME:Logs/WeaponVault.logs}
#logging.file.max-size=30MB
#logging.file.max-history=30

#debug=true

#logging.file.total-size-cap=1GB
#logging.console.enabled=true
#logging.file.enabled=true

#spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}




#Hibernate Multi Tenancy
#spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# Define the Multi-Tenant Provider Classes
#spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.armory.WeaponVault.config.multitenancy.SchemaMultiTenantConnectionProvider
#spring.jpa.properties.hibernate.tenant_identifier_resolver=com.armory.WeaponVault.config.multitenancy.CurrentTenantIdentifierResolverImpl


# JPA/Hibernate settings
# Change to 'validate' or 'none' in production

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.properties.hibernate.default_schema=public


# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sunilbagdawat@gmail.com
spring.mail.password=qbqw jtlz hiqa mfuv
spring.mail.protocol=smtp
spring.mail.smtp.auth=true
spring.mail.smtp.starttls.enable=true
spring.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com