CREATE TABLE IF NOT EXISTS public.organization
(
    organization_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    organization_details jsonb NOT NULL,
    organization_name character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    CONSTRAINT organization_pkey PRIMARY KEY (organization_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.organization
    OWNER to admin;

CREATE TABLE public.super_admins (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) UNIQUE,
	token_expiry timestamp(6) without time zone 	,
	token VARCHAR(255) ,
    created_at timestamp(6) without time zone DEFAULT now(),
    updated_at timestamp(6) without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.admin_invites (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    organization_id BIGINT NOT NULL,
    invited_by_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    sent_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    accepted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    revoked_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(),

    CONSTRAINT fk_organization
        FOREIGN KEY (organization_id)
        REFERENCES public.organization (organization_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_invited_by
        FOREIGN KEY (invited_by_id)
        REFERENCES public.super_admins (id)
        ON DELETE CASCADE
);


