ALTER SCHEMA organization_structure OWNER TO admin;
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE organization_structure.department (
    department_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    department_details jsonb NOT NULL,
    department_name character varying(255),
    updated_at timestamp(6) without time zone
);
ALTER TABLE organization_structure.department OWNER TO admin;
ALTER TABLE organization_structure.department ALTER COLUMN department_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME organization_structure.department_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE organization_structure.inventory (
    inventory_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    inventory_details jsonb NOT NULL,
    serial_no character varying(255),
    updated_at timestamp(6) without time zone,
    category_id bigint NOT NULL
);
ALTER TABLE organization_structure.inventory OWNER TO admin;
ALTER TABLE organization_structure.inventory ALTER COLUMN inventory_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME organization_structure.inventory_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE organization_structure.category (
    category_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    category_details jsonb NOT NULL,
    category_name character varying(255),
    updated_at timestamp(6) without time zone
);


ALTER TABLE organization_structure.category OWNER TO admin;
ALTER TABLE organization_structure.category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME organization_structure.category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY organization_structure.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (department_id);
ALTER TABLE ONLY organization_structure.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (inventory_id);
ALTER TABLE ONLY organization_structure.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (category_id);
ALTER TABLE ONLY organization_structure.inventory
    ADD CONSTRAINT fkp7gj4l80fx8v0uap3b2crjwp5 FOREIGN KEY (category_id) REFERENCES organization_structure.category(category_id);


CREATE TABLE organization_structure.manufacturer (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255),
    status VARCHAR(50),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

CREATE TABLE organization_structure.manufacturer_category (
    manufacturer_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(),
    PRIMARY KEY (manufacturer_id, category_id),
    FOREIGN KEY (manufacturer_id) REFERENCES organization_structure.manufacturer(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES organization_structure.category(category_id) ON DELETE CASCADE
);

