/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.armory.WeaponVault.APIs.adminInvitesApi;

import com.armory.WeaponVault.entityDTO.AdminInviteRequest;
import com.armory.WeaponVault.entityDTO.AdminInviteResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-29T13:52:58.938669090+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "AdminInvite", description = "Operations related to managing SuperAdmin.")
public interface AdminApi {

    default AdminApiDelegate getDelegate() {
        return new AdminApiDelegate() {};
    }

    /**
     * GET /admin/invite : Get all admin invites
     *
     * @return A list of all admin invites (status code 200)
     *         or Forbidden - Access Denied (status code 403)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getAllAdminInvites",
        summary = "Get all admin invites",
        tags = { "AdminInvite" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of all admin invites", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AdminInviteResponse.class)))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden - Access Denied", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/admin/invite",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<AdminInviteResponse>> getAllAdminInvites(
        
    ) {
        return getDelegate().getAllAdminInvites();
    }


    /**
     * POST /admin/invite : Send Admin Invite
     * The POST Admin Invites API endpoint is designed to create a record for admin invites and send an invitation email to the specified admin user. This process involves generating an invite token and sending an email using a predefined template.
     *
     * @param adminInviteRequest  (required)
     * @return Invite sent successfully (status code 201)
     *         or Missing or invalid parameters (status code 400)
     *         or Organization or super admin not found (status code 404)
     *         or Unexpected server error (status code 500)
     */
    @Operation(
        operationId = "sendAdminInvite",
        summary = "Send Admin Invite",
        description = "The POST Admin Invites API endpoint is designed to create a record for admin invites and send an invitation email to the specified admin user. This process involves generating an invite token and sending an email using a predefined template.",
        tags = { "AdminInvite" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Invite sent successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Missing or invalid parameters", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Organization or super admin not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Unexpected server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/admin/invite",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<AdminInviteResponse> sendAdminInvite(
        @Parameter(name = "AdminInviteRequest", description = "", required = true) @Valid @RequestBody AdminInviteRequest adminInviteRequest
    ) {
        return getDelegate().sendAdminInvite(adminInviteRequest);
    }


    /**
     * PUT /admin/invite/{inviteId} : Update Admin Invite
     * The PUT Admin Invites API endpoint is used to update an existing admin invite. This can be used to resend the invitation or update the email/other information for the invite.
     *
     * @param inviteId The unique identifier for the admin invite. (required)
     * @param adminInviteRequest  (required)
     * @return Invite updated successfully (status code 200)
     *         or Missing or invalid parameters (status code 400)
     *         or Invite not found or Organization not found (status code 404)
     *         or Unexpected server error (status code 500)
     */
    @Operation(
        operationId = "updateAdminInvite",
        summary = "Update Admin Invite",
        description = "The PUT Admin Invites API endpoint is used to update an existing admin invite. This can be used to resend the invitation or update the email/other information for the invite.",
        tags = { "AdminInvite" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Invite updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Missing or invalid parameters", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Invite not found or Organization not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Unexpected server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminInviteResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/admin/invite/{inviteId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<AdminInviteResponse> updateAdminInvite(
        @Parameter(name = "inviteId", description = "The unique identifier for the admin invite.", required = true, in = ParameterIn.PATH) @PathVariable("inviteId") Long inviteId,
        @Parameter(name = "AdminInviteRequest", description = "", required = true) @Valid @RequestBody AdminInviteRequest adminInviteRequest
    ) {
        return getDelegate().updateAdminInvite(inviteId, adminInviteRequest);
    }

}
