/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.armory.WeaponVault.organizationApi;

import com.armory.WeaponVault.entityDTO.SuperAdminRequest;
import com.armory.WeaponVault.entityDTO.SuperAdminResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-29T14:12:51.910033071+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "SuperAdmin", description = "Operations related to managing SuperAdmin.")
public interface AuthApi {

    default AuthApiDelegate getDelegate() {
        return new AuthApiDelegate() {};
    }

    /**
     * POST /auth/login : Super Admin Login
     *
     * @param superAdminRequest  (required)
     * @return Successful login (status code 200)
     *         or Missing email or password (status code 400)
     *         or Invalid credentials (status code 401)
     *         or Account disabled (status code 403)
     *         or Super Admin not found (status code 404)
     */
    @Operation(
        operationId = "superAdminLogin",
        summary = "Super Admin Login",
        tags = { "SuperAdmin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful login", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuperAdminResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Missing email or password", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuperAdminResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Invalid credentials", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuperAdminResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Account disabled", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuperAdminResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Super Admin not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuperAdminResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SuperAdminResponse> superAdminLogin(
        @Parameter(name = "SuperAdminRequest", description = "", required = true) @Valid @RequestBody SuperAdminRequest superAdminRequest
    ) {
        return getDelegate().superAdminLogin(superAdminRequest);
    }

}
