/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.armory.WeaponVault.organizationApi;

import com.armory.WeaponVault.entityDTO.CategoryDto;
import com.armory.WeaponVault.entityDTO.CategoryDtoInsert;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-01T14:23:20.376969458+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "Category", description = "Operations related to managing Category.")
public interface CategoryApi {

    default CategoryApiDelegate getDelegate() {
        return new CategoryApiDelegate() {};
    }

    /**
     * POST /category : Create a new category
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param categoryDtoInsert  (required)
     * @return Category created successfully (status code 201)
     *         or Bad request - Missing or invalid data (status code 400)
     *         or Category with the same name already exists (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "createCategory",
        summary = "Create a new category",
        tags = { "Category" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Category created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategoryDtoInsert.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Missing or invalid data"),
            @ApiResponse(responseCode = "409", description = "Category with the same name already exists"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/category",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<CategoryDtoInsert> createCategory(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "CategoryDtoInsert", description = "", required = true) @Valid @RequestBody CategoryDtoInsert categoryDtoInsert
    ) {
        return getDelegate().createCategory(xTenantID, categoryDtoInsert);
    }


    /**
     * DELETE /category/{categoryId} : Delete category by ID
     *
     * @param categoryId ID of the category to delete (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Category deleted successfully (status code 200)
     *         or Category not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "deleteCategory",
        summary = "Delete category by ID",
        tags = { "Category" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Category deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Category not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/category/{categoryId}"
    )
    
    default ResponseEntity<Void> deleteCategory(
        @Parameter(name = "categoryId", description = "ID of the category to delete", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") Long categoryId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().deleteCategory(categoryId, xTenantID);
    }


    /**
     * GET /category : Get all categories
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return A list of categories (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getAllCategories",
        summary = "Get all categories",
        tags = { "Category" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of categories", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CategoryDto.class)))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/category",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<CategoryDto>> getAllCategories(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getAllCategories(xTenantID);
    }


    /**
     * GET /category/{categoryId} : Get category by ID
     *
     * @param categoryId ID of the category to fetch (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Category details by ID (status code 200)
     *         or Category not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getCategoryById",
        summary = "Get category by ID",
        tags = { "Category" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Category details by ID", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategoryDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Category not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/category/{categoryId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<CategoryDto> getCategoryById(
        @Parameter(name = "categoryId", description = "ID of the category to fetch", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") Long categoryId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getCategoryById(categoryId, xTenantID);
    }


    /**
     * PUT /category/{categoryId} : Update category by ID
     *
     * @param categoryId ID of the category to update (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param categoryDtoInsert  (required)
     * @return Category updated successfully (status code 200)
     *         or Category not found (status code 404)
     *         or Bad request - Missing or invalid data (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "updateCategory",
        summary = "Update category by ID",
        tags = { "Category" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Category updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategoryDtoInsert.class))
            }),
            @ApiResponse(responseCode = "404", description = "Category not found"),
            @ApiResponse(responseCode = "400", description = "Bad request - Missing or invalid data"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/category/{categoryId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<CategoryDtoInsert> updateCategory(
        @Parameter(name = "categoryId", description = "ID of the category to update", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") Long categoryId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "CategoryDtoInsert", description = "", required = true) @Valid @RequestBody CategoryDtoInsert categoryDtoInsert
    ) {
        return getDelegate().updateCategory(categoryId, xTenantID, categoryDtoInsert);
    }

}
