/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.armory.WeaponVault.organizationApi;

import com.armory.WeaponVault.entityDTO.DepartmentDto;
import com.armory.WeaponVault.entityDTO.GetAllOrganizations500Response;
import com.armory.WeaponVault.entityDTO.GetDepartmentById404Response;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-30T17:45:15.281186947+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "Departments", description = "Operations related to managing departments.")
public interface DepartmentsApi {

    default DepartmentsApiDelegate getDelegate() {
        return new DepartmentsApiDelegate() {};
    }

    /**
     * POST /departments : Create a new department
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param departmentDto  (required)
     * @return Department created successfully (status code 201)
     *         or Bad request - Missing or invalid data (status code 400)
     *         or Department with same name already present. (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "createDepartment",
        summary = "Create a new department",
        tags = { "Departments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Department created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DepartmentDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Missing or invalid data"),
            @ApiResponse(responseCode = "409", description = "Department with same name already present."),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetAllOrganizations500Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/departments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DepartmentDto> createDepartment(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "DepartmentDto", description = "", required = true) @Valid @RequestBody DepartmentDto departmentDto
    ) {
        return getDelegate().createDepartment(xTenantID, departmentDto);
    }


    /**
     * DELETE /departments/{departmentId} : Delete department by ID
     *
     * @param departmentId ID of the department to delete (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Department deleted successfully (status code 200)
     *         or Department not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "deleteDepartment",
        summary = "Delete department by ID",
        tags = { "Departments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Department deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Department not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetDepartmentById404Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/departments/{departmentId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> deleteDepartment(
        @Parameter(name = "departmentId", description = "ID of the department to delete", required = true, in = ParameterIn.PATH) @PathVariable("departmentId") Long departmentId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().deleteDepartment(departmentId, xTenantID);
    }


    /**
     * GET /departments : Get all departments
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return A list of departments (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getAllDepartments",
        summary = "Get all departments",
        tags = { "Departments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of departments", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = DepartmentDto.class)))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetAllOrganizations500Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/departments",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<DepartmentDto>> getAllDepartments(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getAllDepartments(xTenantID);
    }


    /**
     * GET /departments/{departmentId} : Get department by departmentId
     *
     * @param departmentId ID of the department to fetch (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Department details (status code 200)
     *         or Department not found (status code 404)
     */
    @Operation(
        operationId = "getDepartmentById",
        summary = "Get department by departmentId",
        tags = { "Departments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Department details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DepartmentDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Department not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetDepartmentById404Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/departments/{departmentId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<DepartmentDto> getDepartmentById(
        @Parameter(name = "departmentId", description = "ID of the department to fetch", required = true, in = ParameterIn.PATH) @PathVariable("departmentId") Long departmentId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getDepartmentById(departmentId, xTenantID);
    }


    /**
     * GET /departments/name/{departmentName} : Get department by name
     *
     * @param departmentName  (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Department details (status code 200)
     *         or Department not found (status code 404)
     */
    @Operation(
        operationId = "getDepartmentByName",
        summary = "Get department by name",
        tags = { "Departments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Department details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DepartmentDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Department not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetDepartmentById404Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/departments/name/{departmentName}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<DepartmentDto> getDepartmentByName(
        @Parameter(name = "departmentName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("departmentName") String departmentName,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getDepartmentByName(departmentName, xTenantID);
    }


    /**
     * PUT /departments/{departmentId} : Update department by department Id
     *
     * @param departmentId ID of the department to update (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param departmentDto  (required)
     * @return Department updated successfully (status code 200)
     *         or Department data not found (status code 404)
     *         or Bad request (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "updateDepartment",
        summary = "Update department by department Id",
        tags = { "Departments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Department updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DepartmentDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Department data not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetDepartmentById404Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/departments/{departmentId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DepartmentDto> updateDepartment(
        @Parameter(name = "departmentId", description = "ID of the department to update", required = true, in = ParameterIn.PATH) @PathVariable("departmentId") Long departmentId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "DepartmentDto", description = "", required = true) @Valid @RequestBody DepartmentDto departmentDto
    ) {
        return getDelegate().updateDepartment(departmentId, xTenantID, departmentDto);
    }

}
