/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.armory.WeaponVault.organizationApi;

import com.armory.WeaponVault.entityDTO.InventoryDto;
import com.armory.WeaponVault.entityDTO.InventoryDtoId;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-30T17:45:15.281186947+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "Inventory", description = "Operations related to managing inventories.")
public interface InventoryApi {

    default InventoryApiDelegate getDelegate() {
        return new InventoryApiDelegate() {};
    }

    /**
     * POST /inventory : Create a new inventory
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param inventoryDtoId  (required)
     * @return Inventory created successfully (status code 201)
     *         or Bad request - Missing or invalid data (status code 400)
     *         or Inventory with same serial no is already present. (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "createInventory",
        summary = "Create a new inventory",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Inventory created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InventoryDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Missing or invalid data"),
            @ApiResponse(responseCode = "409", description = "Inventory with same serial no is already present."),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/inventory",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<InventoryDto> createInventory(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "InventoryDtoId", description = "", required = true) @Valid @RequestBody InventoryDtoId inventoryDtoId
    ) {
        return getDelegate().createInventory(xTenantID, inventoryDtoId);
    }


    /**
     * DELETE /inventory/{inventoryId} : Delete inventory by inventoryId
     *
     * @param inventoryId ID of the inventory to delete (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Inventory deleted successfully (status code 200)
     *         or Inventory not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "deleteInventory",
        summary = "Delete inventory by inventoryId",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Inventory deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Inventory not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/inventory/{inventoryId}"
    )
    
    default ResponseEntity<Void> deleteInventory(
        @Parameter(name = "inventoryId", description = "ID of the inventory to delete", required = true, in = ParameterIn.PATH) @PathVariable("inventoryId") Long inventoryId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().deleteInventory(inventoryId, xTenantID);
    }


    /**
     * GET /inventory : Get all inventories
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return A list of Inventories (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getAllInventories",
        summary = "Get all inventories",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of Inventories", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = InventoryDto.class)))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/inventory",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<InventoryDto>> getAllInventories(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getAllInventories(xTenantID);
    }


    /**
     * GET /inventory/category/{categoryId} : Get inventories by categoryId
     *
     * @param categoryId Category ID to fetch associated inventories (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return List of inventories for the specified category ID (status code 200)
     *         or No inventory found for the category (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getInventoriesByCategoryId",
        summary = "Get inventories by categoryId",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of inventories for the specified category ID", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = InventoryDto.class)))
            }),
            @ApiResponse(responseCode = "404", description = "No inventory found for the category"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/inventory/category/{categoryId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<InventoryDto>> getInventoriesByCategoryId(
        @Parameter(name = "categoryId", description = "Category ID to fetch associated inventories", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") Long categoryId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getInventoriesByCategoryId(categoryId, xTenantID);
    }


    /**
     * GET /inventory/{inventoryId} : Get inventory by inventoryId
     *
     * @param inventoryId ID of the inventory to fetch (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Inventory details by inventoryId (status code 200)
     *         or Inventory not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getInventoryById",
        summary = "Get inventory by inventoryId",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Inventory details by inventoryId", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InventoryDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Inventory not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/inventory/{inventoryId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<InventoryDto> getInventoryById(
        @Parameter(name = "inventoryId", description = "ID of the inventory to fetch", required = true, in = ParameterIn.PATH) @PathVariable("inventoryId") Long inventoryId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getInventoryById(inventoryId, xTenantID);
    }


    /**
     * GET /inventory/serial/{serialNo} : Get inventory by serial number
     *
     * @param serialNo Serial number of the inventory to fetch (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Inventory details by serial number (status code 200)
     *         or Inventory not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getInventoryBySerialNo",
        summary = "Get inventory by serial number",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Inventory details by serial number", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InventoryDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Inventory not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/inventory/serial/{serialNo}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<InventoryDto> getInventoryBySerialNo(
        @Parameter(name = "serialNo", description = "Serial number of the inventory to fetch", required = true, in = ParameterIn.PATH) @PathVariable("serialNo") String serialNo,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getInventoryBySerialNo(serialNo, xTenantID);
    }


    /**
     * PUT /inventory/{inventoryId} : Update inventory by inventoryId
     *
     * @param inventoryId ID of the inventory to update (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param inventoryDtoId  (required)
     * @return Inventory updated successfully (status code 200)
     *         or Inventory data not found (status code 404)
     *         or Bad request - Missing or invalid data (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "updateInventory",
        summary = "Update inventory by inventoryId",
        tags = { "Inventory" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Inventory updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InventoryDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Inventory data not found"),
            @ApiResponse(responseCode = "400", description = "Bad request - Missing or invalid data"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inventory/{inventoryId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<InventoryDto> updateInventory(
        @Parameter(name = "inventoryId", description = "ID of the inventory to update", required = true, in = ParameterIn.PATH) @PathVariable("inventoryId") Long inventoryId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "InventoryDtoId", description = "", required = true) @Valid @RequestBody InventoryDtoId inventoryDtoId
    ) {
        return getDelegate().updateInventory(inventoryId, xTenantID, inventoryDtoId);
    }

}
