/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.armory.WeaponVault.organizationApi;

import com.armory.WeaponVault.entityDTO.ManufacturerDto;
import com.armory.WeaponVault.entityDTO.ManufacturerDtoInsert;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-01T14:23:20.376969458+05:30[Asia/Kolkata]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "Manufacturer", description = "Operations related to managing Manufacturer.")
public interface ManufacturerApi {

    default ManufacturerApiDelegate getDelegate() {
        return new ManufacturerApiDelegate() {};
    }

    /**
     * POST /manufacturer : Create a new manufacturer
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param manufacturerDtoInsert  (required)
     * @return Manufacturer created successfully (status code 201)
     *         or Bad request - Missing or invalid data (status code 400)
     *         or Organization with same name already present. (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "createManufacturer",
        summary = "Create a new manufacturer",
        tags = { "Manufacturer" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Manufacturer created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ManufacturerDtoInsert.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Missing or invalid data"),
            @ApiResponse(responseCode = "409", description = "Organization with same name already present."),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/manufacturer",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<ManufacturerDtoInsert> createManufacturer(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "ManufacturerDtoInsert", description = "", required = true) @Valid @RequestBody ManufacturerDtoInsert manufacturerDtoInsert
    ) {
        return getDelegate().createManufacturer(xTenantID, manufacturerDtoInsert);
    }


    /**
     * DELETE /manufacturer/{manufacturerId} : Delete manufacturer by manufacturerId
     *
     * @param manufacturerId ID of the manufacturer to delete (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Manufacturer deleted successfully (status code 200)
     *         or Manufacturer not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "deleteManufacturer",
        summary = "Delete manufacturer by manufacturerId",
        tags = { "Manufacturer" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Manufacturer deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Manufacturer not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/manufacturer/{manufacturerId}"
    )
    
    default ResponseEntity<Void> deleteManufacturer(
        @Parameter(name = "manufacturerId", description = "ID of the manufacturer to delete", required = true, in = ParameterIn.PATH) @PathVariable("manufacturerId") Long manufacturerId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().deleteManufacturer(manufacturerId, xTenantID);
    }


    /**
     * GET /manufacturer : Get all manufacturers
     *
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return A list of manufacturers (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getAllManufacturers",
        summary = "Get all manufacturers",
        tags = { "Manufacturer" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of manufacturers", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ManufacturerDto.class)))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/manufacturer",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<ManufacturerDto>> getAllManufacturers(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getAllManufacturers(xTenantID);
    }


    /**
     * GET /manufacturer/{manufacturerId} : Get manufacturer by manufacturerId
     *
     * @param manufacturerId ID of the manufacturer to fetch (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @return Manufacturer details by manufacturerId (status code 200)
     *         or Manufacturer not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getManufacturerById",
        summary = "Get manufacturer by manufacturerId",
        tags = { "Manufacturer" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Manufacturer details by manufacturerId", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ManufacturerDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Manufacturer not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/manufacturer/{manufacturerId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ManufacturerDto> getManufacturerById(
        @Parameter(name = "manufacturerId", description = "ID of the manufacturer to fetch", required = true, in = ParameterIn.PATH) @PathVariable("manufacturerId") Long manufacturerId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID
    ) {
        return getDelegate().getManufacturerById(manufacturerId, xTenantID);
    }


    /**
     * PUT /manufacturer/{manufacturerId} : Update manufacturer by manufacturerId
     *
     * @param manufacturerId ID of the manufacturer to update (required)
     * @param xTenantID Tenant identifier for multi-tenancy. (required)
     * @param manufacturerDtoInsert  (required)
     * @return Manufacturer updated successfully (status code 200)
     *         or Manufacturer not found (status code 404)
     *         or Bad request - Missing or invalid data (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "updateManufacturer",
        summary = "Update manufacturer by manufacturerId",
        tags = { "Manufacturer" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Manufacturer updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ManufacturerDtoInsert.class))
            }),
            @ApiResponse(responseCode = "404", description = "Manufacturer not found"),
            @ApiResponse(responseCode = "400", description = "Bad request - Missing or invalid data"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/manufacturer/{manufacturerId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<ManufacturerDtoInsert> updateManufacturer(
        @Parameter(name = "manufacturerId", description = "ID of the manufacturer to update", required = true, in = ParameterIn.PATH) @PathVariable("manufacturerId") Long manufacturerId,
        @NotNull @Parameter(name = "X-Tenant-ID", description = "Tenant identifier for multi-tenancy.", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(name = "ManufacturerDtoInsert", description = "", required = true) @Valid @RequestBody ManufacturerDtoInsert manufacturerDtoInsert
    ) {
        return getDelegate().updateManufacturer(manufacturerId, xTenantID, manufacturerDtoInsert);
    }

}
